// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/user.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace userservice {
  public static partial class UserLogin
  {
    static readonly string __ServiceName = "UserLogin";

    static readonly grpc::Marshaller<global::userservice.UserRequest> __Marshaller_UserRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::userservice.UserRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::userservice.UserResponse> __Marshaller_UserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::userservice.UserResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::userservice.UserRequest, global::userservice.UserResponse> __Method_Login = new grpc::Method<global::userservice.UserRequest, global::userservice.UserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_UserRequest,
        __Marshaller_UserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::userservice.UserReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserLogin</summary>
    public abstract partial class UserLoginBase
    {
      public virtual global::System.Threading.Tasks.Task<global::userservice.UserResponse> Login(global::userservice.UserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UserLogin</summary>
    public partial class UserLoginClient : grpc::ClientBase<UserLoginClient>
    {
      /// <summary>Creates a new client for UserLogin</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserLoginClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserLogin that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserLoginClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserLoginClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserLoginClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::userservice.UserResponse Login(global::userservice.UserRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::userservice.UserResponse Login(global::userservice.UserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::userservice.UserResponse> LoginAsync(global::userservice.UserRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::userservice.UserResponse> LoginAsync(global::userservice.UserRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UserLoginClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserLoginClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UserLoginBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login).Build();
    }

  }
}
#endregion
